### ISSUE TITLE
Git object id must be byte or a text string, not: NoneType

### ISSUE THREAD

**Issue by nkhine** [hforge/ikaaro#1]
i get this error when i try to build the 0.75 ikaaro

```
  2012-05-31 22:30:00 freebsd.local itools.database[88273]: Transaction failed
  Traceback (most recent call last):
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 507, in save_changes
    self._save_changes(data)
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 473, in _save_changes
    self.worktree.git_commit(git_msg, git_author, git_date)
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 343, in git_commit
    name = self.username
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/core/lazy.py", line 33, in __get__
    value = self.meth(instance)
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 310, in username
    return self._call(cmd).rstrip()
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 94, in _call
    raise EnvironmentError, (popen.returncode, stderrdata)
  EnvironmentError: [Errno 1] 

2012-05-31 22:30:00 ns230183.ovh.net itools.database[88273]: Aborting failed
  Traceback (most recent call last):
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 511, in save_changes
    self._abort_changes()
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 415, in _abort_changes
    self.worktree.git_reset()
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 443, in git_reset
    tree_oid = self.lookup(head).tree.oid
    File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 174, in lookup
    cache[sha] = self.repo[sha]
  TypeError: Git object id must be byte or a text string, not: NoneType

Traceback (most recent call last):
  File "/home/khine/.virtualenvs/itools/bin/icms-init.py", line 226, in <module>
    init(parser, options, target)
  File "/home/khine/.virtualenvs/itools/bin/icms-init.py", line 173, in init
    database.save_changes()
  File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 511, in save_changes
    self._abort_changes()
  File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/database/rw.py", line 415, in _abort_changes
    self.worktree.git_reset()
  File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 443, in git_reset
    tree_oid = self.lookup(head).tree.oid
  File "/home/khine/.virtualenvs/itools/lib/python2.7/site-packages/itools/git/worktree.py", line 174, in lookup
    cache[sha] = self.repo[sha]
  TypeError: Git object id must be byte or a text string, not: NoneType
```

but it creates the files:

```
  ls -al
  total 11
  drwxr-xr-x  5 khine  staff   8 May 31 22:30 .
  drwxr-xr-x  6 khine  staff   7 May 31 22:30 ..
  drwxr-xr-x  6 khine  staff  10 May 31 22:30 .git
  -rw-r--r--  1 khine  staff  62 May 31 22:30 .metadata
  drwxr-xr-x  6 khine  staff  19 May 31 22:30 config
  -rw-r--r--  1 khine  staff  97 May 31 22:30 config.metadata
  drwxr-xr-x  2 khine  staff   3 May 31 22:30 users
  -rw-r--r--  1 khine  staff  61 May 31 22:30 users.metadata


    $git status
# On branch master
#
# Initial commit
#
# Changes to be committed:
#   (use "git rm --cached <file>..." to unstage)
#
#       new file:   .metadata
#       new file:   config.metadata
#       new file:   config/access.metadata
#       new file:   config/access/0.metadata
#       new file:   config/access/1.metadata
#       new file:   config/access/2.metadata
#       new file:   config/access/3.metadata
#       new file:   config/access/4.metadata
#       new file:   config/access/5.metadata
#       new file:   config/access/6.metadata
#       new file:   config/captcha.metadata
#       new file:   config/captcha/question.metadata
#       new file:   config/captcha/recaptcha.metadata
#       new file:   config/footer.data.en
#       new file:   config/footer.metadata
#       new file:   config/groups.metadata
#       new file:   config/groups/admins.metadata
#       new file:   config/groups/members.metadata
#       new file:   config/groups/reviewers.metadata
#       new file:   config/mail.metadata
#       new file:   config/menu.metadata
#       new file:   config/menu/contact.metadata
#       new file:   config/menu/home.metadata
#       new file:   config/register.metadata
#       new file:   config/seo.metadata
#       new file:   config/theme.banner
#       new file:   config/theme.logo
#       new file:   config/theme.metadata
#       new file:   config/theme.style
#       new file:   users.metadata
#       new file:   users/0.metadata
```

the if i commit the files manually the server start but i am unable to login as it does not recognise the password.

**Comment by staverne** [comment]
Please upgrade libgit2 / pygit2 versions.
There was blocking changes.
Now pygit2 is available in PIP
